"""
LLM utilities for PaperIQ.

This module sends prompts to Gemini and 
returns generated responses.
"""
import streamlit as st
import google.generativeai as genai

@st.cache_resource
def load_llm():
    """
    Load and cache the gemini model.

    Returns: 
        GenerativeModel:
            Initialized Gemini model.
    """
    genai.configure(api_key=st.secrets["GEMINI_API_KEY"])
    return genai.GenerativeModel("gemini-2.5-flash")

llm = load_llm()

def generate_response(prompt: str) ->str:
    """
    Generate an answer using gemini.

    Args:
        Prompt (str):
            prompt generated by the prompt builder.

    Returns:
        str: Model response.
    """
    response = llm.generate_content(prompt)

    return response.text